services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  postgres-doctor:
    image: postgres:17-alpine
    container_name: postgres-doctor
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: doctor
    ports:
      - "5432:5432"
    volumes:
      - postgres-doctor-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-appointment:
    image: postgres:17-alpine
    container_name: postgres-appointment
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: appointments
    ports:
      - "5433:5432"
    volumes:
      - postgres-appointment-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  doctor-service:
    build: ./doctor-service
    container_name: doctor-service
    depends_on:
      postgres-doctor:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "50051:50051"
    environment:
      DATABASE_URL: "postgres://postgres:admin@postgres-doctor:5432/doctor?sslmode=disable&timezone=Asia/Almaty"
      GRPC_PORT: "50051"
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
      REDIS_URL: "redis://redis:6379"
      CACHE_TTL_SECONDS: 3600

  appointment-service:
    build: ./appointment-service
    container_name: appointment-service
    depends_on:
      postgres-appointment:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      doctor-service:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - "50052:50052"
    environment:
      DATABASE_URL: "postgres://postgres:admin@postgres-appointment:5432/appointments?sslmode=disable&timezone=Asia/Almaty"
      DOCTOR_SERVICE_URL: "doctor-service:50051"
      GRPC_PORT: "50052"
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
      REDIS_URL: "redis://redis:6379"
      CACHE_TTL_SECONDS: 3600

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
      GATEWAY_URL: "http://mock-gateway:8080"
      WORKER_POOL_SIZE: "5"
      REDIS_URL: "redis://redis:6379"
      CACHE_TTL_SECONDS: 3600
      
  mock-gateway:
    build: ./mock-gateway
    container_name: mock-gateway
    depends_on:
      doctor-service:
        condition: service_started
      appointment-service:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      GATEWAY_PORT: "8080"

volumes:
  postgres-doctor-data:
  postgres-appointment-data: